# Generated by Django 4.1.5 on 2023-02-02 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.TextField(primary_key=True, serialize=False)),
                ('time', models.IntegerField(null=True)),
                ('round', models.TextField(null=True)),
                ('score', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, null=True)),
                ('surname', models.CharField(max_length=10, null=True)),
                ('hand', models.CharField(max_length=1, null=True)),
                ('height', models.IntegerField(null=True)),
                ('birth', models.DateField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenis.country')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.TextField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30, null=True)),
                ('surface', models.TextField(choices=[('g', 'Grass'), ('h', 'Hard'), ('c', 'Clay')], null=True)),
                ('draw_size', models.IntegerField(choices=[(128, 'D128'), (64, 'D64'), (32, 'D32'), (8, 'D8'), (4, 'D4')], null=True)),
                ('date', models.DateField(null=True)),
                ('level', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_points', models.IntegerField(null=True)),
                ('player_rank', models.IntegerField(null=True)),
                ('aces', models.IntegerField(null=True)),
                ('double_faults', models.IntegerField(null=True)),
                ('serve_points', models.IntegerField(null=True)),
                ('first_serve', models.IntegerField(null=True)),
                ('first_won', models.IntegerField(null=True)),
                ('second_won', models.IntegerField(null=True)),
                ('serves_game', models.IntegerField(null=True)),
                ('bp_saved', models.IntegerField(null=True)),
                ('bp_faced', models.IntegerField(null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenis.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenis.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='losers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='tenis.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tourney_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenis.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='winners_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tenis.player'),
        ),
    ]
